name: login
description: Microfrontend Login de la aplicación Flutter.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.7.0
  webview_flutter_web: ^0.2.2
  webview_flutter_wkwebview: ^3.0.4

  provider: ^6.1.2 # Alineado con el chasis y home

  http: ^1.2.0

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0

  shared_preferences: ^2.2.2

  go_router: ^13.2.0

  flutter_secure_storage: ^9.2.2

  flutter_animate: ^4.3.0

  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
