name: login
description: Microfrontend de la página de inicio de sesión.

publish_to: 'none' # 🔧 No se publica, será orquestado por `chasis`.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  # 📌 🔄 Manejo de estado con BLoC
  flutter_bloc: ^8.1.3  

  # 📌 🌍 Navegación con `go_router`
  go_router: ^10.1.2  

  # 📌 📡 Cliente HTTP para enviar credenciales a `chasis`
  dio: ^5.3.2         

  # 📌 🔐 Almacenamiento seguro del token de autenticación
  flutter_secure_storage: ^8.0.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
